services:
  python:
    container_name: python1
    build: .
    volumes:
      - '.:/code'
      - '//t/SPE_DAO:/media/Library/SPE_DAO'
      - '~/.iiiflow.yml:/root/.iiiflow.yml:ro'
    working_dir: /code
    command: tail -f /dev/null  # Keep the container running indefinitely for manual commands

  test:
    container_name: python_test
    build: .
    volumes:
      - '.:/code'
      - '//t/SPE_DAO:/media/Library/SPE_DAO'
    working_dir: /code
    command: bash -c "pip install -e . && pytest tests -vv"