services:
  python:
    container_name: python1
    build: .
    volumes:
      - '.:/code'
      - '//t/SPE_DAO:/media/Library/SPE_DAO'
      - '~/.iiiflow.yml:/root/.iiiflow.yml:ro'
    working_dir: /code
    command: tail -f /dev/null  # Keep the container running indefinitely for manual commands

  tests:
    image: arclight-integration:test
    build: .
    volumes:
      - '.:/code'
      - '//t/SPE_DAO:/media/Library/SPE_DAO'
    working_dir: /code
    command: pytest tests -vv

  test-manifest:
    image: arclight-integration:test
    build: .
    volumes:
      - '.:/code'
      - '//t/SPE_DAO:/media/Library/SPE_DAO'
    working_dir: /code
    command: pytest tests/test_08_manifest.py -vv

  test-pdf:
    image: arclight-integration:test
    build: .
    volumes:
      - '.:/code'
      - '//t/SPE_DAO:/media/Library/SPE_DAO'
    working_dir: /code
    command: pytest tests/test_04_pdf.py -vv

  test-tesseract:
    image: arclight-integration:test
    build: .
    volumes:
      - '.:/code'
      - '//t/SPE_DAO:/media/Library/SPE_DAO'
    working_dir: /code
    command: pytest tests/test_06_tesseract.py -vv

  test-transcription:
    image: arclight-integration:test
    build: .
    volumes:
      - '.:/code'
      - '//t/SPE_DAO:/media/Library/SPE_DAO'
    working_dir: /code
    command: pytest tests/test_07_transcription.py -vv

  test-conversions:
    image: arclight-integration:test
    build: .
    volumes:
      - '.:/code'
      - '//t/SPE_DAO:/media/Library/SPE_DAO'
    working_dir: /code
    command: pytest tests/test_01_conversions.py -vv

  test-metadata:
    image: arclight-integration:test
    build: .
    volumes:
      - '.:/code'
      - '//t/SPE_DAO:/media/Library/SPE_DAO'
    working_dir: /code
    command: pytest tests/test_02_metadata.py -vv

  test-thumbnail:
    image: arclight-integration:test
    build: .
    volumes:
      - '.:/code'
      - '//t/SPE_DAO:/media/Library/SPE_DAO'
    working_dir: /code
    command: pytest tests/test_03_thumbnail.py -vv

  test-ptif:
    image: arclight-integration:test
    build: .
    volumes:
      - '.:/code'
      - '//t/SPE_DAO:/media/Library/SPE_DAO'
    working_dir: /code
    command: pytest tests/test_05_ptif.py -vv
