services:
  python:
    container_name: python1
    build: .
    volumes:
      - '.:/code'
      - '//t/SPE_DAO:/media/Library/SPE_DAO'
    working_dir: /code
    command: bash
    tty: true
    stdin_open: true
